import { Routes } from '@angular/router';
import { Dashboard } from './components/dashboard/dashboard';
import { BookListComponent } from './components/book-list/book-list.component';
import { BookFormComponent } from './components/book-form/book-form.component';
import { AuthorListComponent } from './components/author-list/author-list.component';
import { AuthorFormComponent } from './components/author-form/author-form.component';

import { AuthorDetailsComponent } from './components/author-details/author-details';
import { BookDetailsComponent } from './components/book-details/book-details';
import { BookSummaryComponent } from './components/book-summary/book-summary';
import { TagManagementComponent } from './components/tag-management/tag-management.component';
import { SessionLogComponent } from './components/session-log/session-log.component';
import { HeatmapComponent } from './components/heatmap/heatmap';
import { StatisticsComponent } from './components/statistics/statistics';
export const routes: Routes = [
    { path: '', component: Dashboard },
    { path: 'books', component: BookListComponent },
    { path: 'books/new', component: BookFormComponent },
    { path: 'books/:id/edit', component: BookFormComponent },
    { path: 'books/:id/summary', component: BookSummaryComponent },
    { path: 'books/:id', component: BookDetailsComponent },
    { path: 'authors', component: AuthorListComponent },
    { path: 'authors/new', component: AuthorFormComponent },
    { path: 'authors/:id/edit', component: AuthorFormComponent },
    { path: 'authors/:id', component: AuthorDetailsComponent },
    { path: 'tags', component: TagManagementComponent },
    { path: 'books/:bookId/session/log', component: SessionLogComponent },
    { path: 'heatmap', component: HeatmapComponent },
    { path: 'statistics', component: StatisticsComponent }
];
